[project]
name = "living_doc_py"
description = "to poke living-documentation concepts in Python"
version = "0.1.0"
authors = [
    { name = "Mehdi Houacine", email = "mehdihouacine7@gmail.com" }
]
dependencies = [
    'click >= 8.1.3',
    'xlsxwriter >= 3.1.0',
]

[project.optional-dependencies]
tests = [
    'pytest >= 7.3.1',
]
dev=['black', 'ruff >= 0.0.262', 'build >= 0.10.0', "wheel"]

[tool.setuptools]
py-modules = ["living_doc"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.scripts]
living-glossary = "living_doc.app:cli"

[tool.ruff]
select = ["E", "F"]
ignore = ["E501"]
