[project]
name = "living_doc_py"
description = "to poke living-documentation concepts in Python"
version = "0.1.0"
authors = [
    { name = "Mehdi Houacine", email = "mehdihouacine7@gmail.com" }
]
dependencies = [
    "wheel"
]

[project.optional-dependencies]
tests = [
    'pytest >= 7.3.1',
    'click >= 8.1.3',
    'xlsxwriter >= 3.1.0',
]
dev=['black', 'ruff>= 0.0.262']

[tool.setuptools]
py-modules = ["living_doc"]

[tool.ruff]
select = ["E", "F"]
ignore = ["E501"]
